[project]
name = "sys-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mailjet-rest>=1.5.1",
    "psutil>=7.1.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
